---
  - hosts: nas

    vars:
      image_name: "jenkins-dind:latest"
      container_name: "jenkins"
      ports: "-p 8888:8080"
      volumes:  "-v /volume2/docker/jenkins:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock"

    tasks:
      - name: docker stop 
        command: "/usr/local/bin/docker container stop {{ container_name }}"
        ignore_errors: yes
      - name: wait for container to stop
        pause:
          seconds: 12
      - name: docker run
        command: "/usr/local/bin/docker run --rm -d {{ ports }} {{ volumes }} --name {{ container_name }} {{ image_name }}"
      - name: docker container ls 
        command: "/usr/local/bin/docker container ls -f name={{ container_name }}"
        register: result
      - debug:
          msg: "{{ result.stdout_lines }}"
    