---
  - hosts: nas

    vars:
      image_name: "jenkins/jenkins"
      container_name: "jenkins"
      ports: "-p 8888:8080 -p 50000:50000"
      volumes:  "-v /your/:/var/jenkins_home"

    tasks:
      - name: docker pull image
        command: "/usr/local/bin/docker pull jenkins:latest"
      - name: docker stop 
        command: "/usr/local/bin/docker container stop {{ container_name }}"
        ignore_errors: yes
      - name: docker container 
        command: "/usr/local/bin/docker run --rm -d {{ ports }} --name {{ container_name }} {{ image_name }}"
      - name: docker run nginx
        command: "/usr/local/bin/docker container ls -f name={{ container_name }}"